services:
  - type: web
    name: iut-request-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install --include=dev && npm run build
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: bonmnmcjr2mfxbcnd3ij-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: ujgz5vncge7mzokx
      - key: DB_PASSWORD
        value: SLJkJhC4TohLq7lXzg3J
      - key: DB_NAME
        value: bonmnmcjr2mfxbcnd3ij
      - key: JWT_SECRET
        generateValue: true

